name: sfdx

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Salesforce SFDX CLI Action
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{secrets.SFDXAUTH}}
      - name: test sfdx
        run: |
          sfdx --version
          sfdx auth:list
          
          npm --version
