name: SFDX-2
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
            args: 'force:project:create'
