name: yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          pip install shyaml

          cat approvers.yml | shyaml approvers-0 | \
          while read -r -d $'\0' approver; do
              echo "RECEIVED: '$approver'"
          done
