name: yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          pip install shyaml


          cat approvers.yml | shyaml values-0 | \
          while read -r -d $'\0' value; do
              echo "RECEIVED: '$value'"
          done
          
          cat approvers.yml | shyaml get-value approvers[0]
          
