name: yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: payload
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
      - name: Run a one-line script
        run: |


          readarray identityMappings < <(yq e -o=j -I=0 '.approvers[]' approvers.yml )
          
          echo siema $identityMappings[0]

          for identityMapping in "${identityMappings[@]}"; do
            echo "$identityMapping"
          done

